application: extract-product-info
version: 1
runtime: go
api_version: go1

handlers:

# The root URL (/) is handled by the Go application. No other URLs match this pattern.
- url: /app
  static_dir: app

# All other URLs are handled by the Go application.
- url: /js
  static_files: js/index.html
  upload: js/index.html
- url: /go
  static_files: go/index.html
  upload: go/index.html
- url: /.*
  script: _go_app